name = "paper-2024-structured_mesh_coupled"
authors = ["Michael Schlottke-Lakemper <michael.schlottke-lakemper@uni-a.de>", "Simon Candelaresi <simon.candelaresi@uni-a.de>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqLowStorageRK = "b0944070-b475-4768-8dec-fb6eb410534d"
OrdinaryDiffEqSSPRK = "669c94d9-1f4b-4b64-b377-1aa079aa2388"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"
Trixi2Vtk = "bc1476a1-1ca6-4cc3-950b-c312b255ff95"

[compat]
OrdinaryDiffEq = "6.66.0"
